#!/bin/zsh

function @ {
    echo "$@"
    $@
}

alias ALL=
alias LINUX=true
alias HOME=true
alias MAC=true
alias WORK=true

if [[ ! -f self ]]; then
    if [[ $(uname) == "Darwin" ]]; then
        echo -n "platform [MAC]: "
        read PLATFORM
        echo ${PLATFORM:-MAC} >> self
    else
        echo -n "platform [LINUX]: "
        read PLATFORM
        echo ${PLATFORM:-LINUX} >> self
    fi
    echo -n "place [HOME]: "
    read PLACE
    echo ${PLACE:-HOME} >> self
fi
cat self | while read LINE; do
    alias $LINE=
done

setopt ERR_EXIT
export ZSH=$(dirname $0)
for config_file ($ZSH/**/*.install) source $config_file
